### ISSUE TITLE
MethodError: no method matching show

### ISSUE THREAD

**Issue by ryszard314159** [mojaie/MolecularGraph.jl_notebook#2]
MethodError: no method matching show(::Base.PipeEndpoint, ::MIME{Symbol("image/svg+xml")}, ::String)

I am getting the error above while running the snippet of code from [Getting Started](https://nbviewer.jupyter.org/github/mojaie/MolecularGraph.jl_notebook/blob/master/notebook/gettingStarted.ipynb):
```
mol = sdftomol(joinpath(data_dir, "Cefditoren Pivoxil.mol"))
molsvg = drawsvg(mol, 300, 300)
display("image/svg+xml",  molsvg
```

**Comment by mojaie** [comment]
Thank you for trying the tutorial.
I'm sorry that README.md document is still not so helpful.

Do you use Jupyter Notebook with Julia kernel ?
If not, please set up Julia kernel according to IJulia instruction.
https://github.com/JuliaLang/IJulia.jl

Or, you can get SVG file by `write(open(OUTPUT_DIR, "w"), molsvg)` instead.

**Comment by ryszard314159** [comment]
Hi Seiji,

Thank you for your reply. Yes

Pkg.add("IJulia")

solved my problem...

Thanks again!
Ryszard
Ryszard Czerminski
508-358-6328
***@***.***
LinkedIn.com/in/Ryszard.Czerminski
<http://LinkedIn.com/in/RyszardCzerminski>
