### ISSUE TITLE
Transform mol to smiles

### ISSUE THREAD

**Issue by Leticia-maria** [mojaie/MolecularGraph.jl_notebook#5]
Hello, I've checked the documentation, but I haven't found any method that transforms mol to smiles, only smiles to mol.

**Comment by mojaie** [comment]
Yes, unfortunately mol to smiles is not implemented yet...
https://github.com/mojaie/MolecularGraph.jl/issues/23

**Comment by Leticia-maria** [comment]
Could I submit a PR implementing it?

**Comment by mojaie** [comment]
Yes, I would be happy if you make a PR.

**Comment by Leticia-maria** [comment]
https://github.com/dakoner/keras-molecules/blob/dbbb790e74e406faa70b13e8be8104d9e938eba2/convert_rdkit_to_networkx.py

**Comment by Leticia-maria** [comment]
Strategy: https://stackoverflow.com/questions/51195392/smiles-from-graph

**Comment by Leticia-maria** [comment]
> Yes, I would be happy if you make a PR.

@mojaie Please, could you assign me on this issue? I'm working to implement it
